use_frameworks!

platform :ios, '8.0'

target 'JKWechatHelper_Example' do
  pod 'JKWechatHelper', :path => '../'

  target 'JKWechatHelper_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
